- title: '7th ACM SIGPLAN International Symposium on Scala'
  short: Scala
  year: 2016
  url: https://conf.researchr.org/track/scala-2016/scala-2016
  role: Organizer and PC co-chair

- title: '27th European Conference on Artificial Intelligence'
  short: ECAI
  year: 2024
  url: https://www.ecai2024.eu/
  role: PC member

- title: '34th Nordic Workshop on Programming Theory'
  short: NWPT
  year: 2023
  url: https://conf.researchr.org/home/nwpt-2023
  role: PC member

- title: 'ACM SIGPLAN International Conference on Generative Programming: Concepts & Experiences'
  short: GPCE
  year: 2023
  url: https://2023.splashcon.org/home/gpce-2023
  role: PC member

- title: '33nd Nordic Workshop on Programming Theory'
  short: NWPT
  year: 2022
  url: https://nwpt.w.uib.no/
  role: PC member

- title: '32nd Nordic Workshop on Programming Theory'
  short: NWPT
  year: 2021
  url: http://icetcs.ru.is/nwpt21/
  role: PC member

- title: '20th International Conference on Generative Programming: Concepts & Experiences'
  short: GPCE
  year: 2021
  url: https://conf.researchr.org/home/gpce-2021
  role: PC member

- title: '24th ACM SIGPLAN International Conference on Functional Programming'
  short: ICFP
  year: 2019
  url: https://icfp19.sigplan.org/
  role: ERC member

- title: '10th ACM SIGPLAN International Symposium on Scala'
  short: Scala
  year: 2019
  url: https://2019.ecoop.org/home/scala-2019
  role: Steering committee member

- title: '9th ACM SIGPLAN International Symposium on Scala'
  short: Scala
  year: 2018
  url: https://conf.researchr.org/track/scala-2018/scala-2018-papers
  role: Steering committee member

- title: '8th ACM SIGPLAN International Symposium on Scala'
  short: Scala
  year: 2017
  url: https://conf.researchr.org/track/scala-2017/scala-2017-papers
  role: Steering committee member

- title: 'Journal of Logical and Algebraic Methods in Programming'
  short: JLAMP
  year: 2021 &ndash; 2022
  url: https://www.journals.elsevier.com/journal-of-logical-and-algebraic-methods-in-programming
  role: Journal reviewer

- title: 'Journal of Functional Programming'
  short: JFP
  year: '2017 &ndash; 2018'
  url: https://www.cambridge.org/core/journals/journal-of-functional-programming
  role: Journal reviewer

- title: 'IEEE/ACM Transactions on Computational Biology and Bioinformatics'
  short: TCBB
  year: 2018
  url: https://ieeexplore.ieee.org/xpl/aboutJournal.jsp?punumber=8857
  role: Journal reviewer

- title: '30th Static Analysis Symposium'
  short: SAS
  year: 2023
  url: https://conf.researchr.org/home/sas-2023
  role: Sub-reviewer

- title: '35th International Conference on Computer Aided Verification'
  short: CAV
  year: 2023
  url: http://www.i-cav.org/2023/
  role: Sub-reviewer

- title: '24th International Conference on Verification, Model Checking, and Abstract Interpretation'
  short: VMCAI
  year: 2023
  url: https://popl23.sigplan.org/home/VMCAI-2023
  role: Sub-reviewer

- title: '31st European Symposium on Programming'
  short: ESOP
  year: 2022
  url: https://etaps.org/2022/esop
  role: Sub-reviewer

- title: '34th IEEE Computer Security Foundations Symposium'
  short: CSF
  year: 2021
  url: https://www.ieee-security.org/TC/CSF2021/
  role: Sub-reviewer

- title: '47th ACM SIGPLAN Symposium on Principles of Programming Languages'
  short: POPL
  year: 2020
  url: https://popl20.sigplan.org/
  role: Sub-reviewer

- title: '27th European Symposium on Programming'
  short: ESOP
  year: 2018
  url: https://etaps.org/2018/esop
  role: Sub-reviewer

- title: '3rd World Congress on Formal Methods'
  short: FM
  year: 2019
  url: https://formalmethods2019.inesctec.pt/
  role: Sub-reviewer

- title: '19th International Conference on Foundations of Software Science and Computation Structures'
  short: FoSSaCS
  year: 2016
  url: https://etaps.org/2016/fossacs
  role: Sub-reviewer

- title: 'ML Family Workshop'
  short: ML
  year: 2016
  url: http://www.mlworkshop.org/workshops/ml2016
  role: Sub-reviewer

- title: '23rd EACSL Annual Conference on Computer Science Logic and 29th Annual ACM/IEEE Symposium on Logic in Computer Science'
  short: CSL-LICS
  year: 2014
  url: http://lics.siglog.org/csl-lics14/
  role: Sub-reviewer

- title: '7th International Symposium on High-level Parallel Programming and Applications'
  short: HLPP
  year: 2014
  url: https://sites.google.com/site/hlpp2014amsterdam/
  role: Sub-reviewer

- title: '19th ACM SIGPLAN International Conference on Functional Programming'
  short: ICFP
  year: 2014
  url: http://icfpconference.org/icfp2014/
  role: Sub-reviewer
